config/routes.rb
PropertyManagement::Application.routes.draw do

  root 'home#index'

  resources :buildings
  resources :owners

end

app/models/building.rb
class Building < ActiveRecord::Base

  belongs_to :owner,
    inverse_of: :buildings

  validates :street_address, presence: true
  validates :city, presence: true
  validates :state, presence: true
  validates :postal_code, presence: true


end

app/models/owner.rb
class Owner < ActiveRecord::Base

  has_many :buildings,
    inverse_of: :owner,
    dependent: :destroy

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true, uniqueness: {case_sensitive: false}

def full_name
  "#{self.first_name} #{self.last_name}"

end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/buildings_controller.rb
class BuildingsController < ApplicationController

  def index



  end


  def new
    @building = Building.new

  end

  def create
    @building = Building.new(building_params)
    if @building.save
      redirect_to root_path,
      notice: "New Building Successfully Created!"
    else
      render new

    end
  end







  protected

  def building_params
    params.require(:building).permit(:street_address, :city, :state, :postal_code, :description, :owner_id)

  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index


  end

end

app/controllers/owners_controller.rb
class OwnersController < ApplicationController

  def new
    @owner = Owner.new

  end

  def create
    @owner = Owner.new(owner_params)
    if @owner.save
      redirect_to root_path,
      notice: "New Owner Successfully Created!"
    else
      render new
    end
  end


  protected

  def owner_params
    params.require(:owner).permit(:first_name, :last_name, :email, :company)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/building_helper.rb
module BuildingHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/owners_helper.rb
module OwnersHelper
end

app/views/buildings/_building.html.erb
<%= "Can't be blank" %>

app/views/buildings/new.html.erb
<%= simple_form_for (@building) do |f| %>

  <%= f.input :street_address%>
  <%= f.input :city%>
  <%= f.input :state %>
  <%= f.input :postal_code %>
  <%= f.input :description, required: false %>
  <%= f.association :owner, collection: Owner.all, label_method: :full_name, value_method: :id%>
  <%= f.button :submit, "Create New Building"  %>
<%end%>

app/views/home/index.html.erb
<li><%= link_to 'Add New Building', new_building_path %></li>
<li><%= link_to 'Add New Owner', new_owner_path %></li>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
    <% if msg.is_a?(String) %>
      <div data-alert class="alert-box round <%= name.to_s == 'notice' ? 'success' : 'alert' %>">
      <%= content_tag :div, msg %>
      <a href="#" class="close">&times;</a>
    </div>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <%= render 'layouts/messages' %>
    <%= yield %>
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/owners/_owner.html.erb
<%= "Can't be blank" %>

app/views/owners/new.html.erb
<%= simple_form_for (@owner) do |f| %>

  <%= f.input :first_name%>
  <%= f.input :last_name%>
  <%= f.input :email %>
  <%= f.input :company, required: false %>
  <%= f.button :submit, "Create New Owner"  %>
<%end%>